name: Deploy mkdocs website to GitHub Pages

on:
    workflow_dispatch:
        inputs:
                version:
                    description: 'Documentation version (e.g., 1.0.0)'
                    required: true
                    type: string

                set_default:
                    description: 'Set as default version'
                    required: false
                    type: boolean
                    default: false

jobs:
    build-and-deploy-docs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout your branch
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install protoc
              uses: ./.github/workflows/install-rust-and-protoc
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Fetch gh-pages branch
              run: git fetch origin gh-pages --depth=1

            - name: Configure Git for mike
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"

            - name: Set version and set_default variables
              run: |
                echo "DOCS_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
                echo "DOCS_SET_DEFAULT=false" >> $GITHUB_ENV


            - name: Install dependencies and build docs
              run: ./docs/build-docs.sh deploy
